### ISSUE TITLE
Edge closes unexpectedly when opening pdf files

### ISSUE THREAD

**Issue by marcelomijas** [szanuj/blank-new-tab#1]
Settings:
- Blank New Tab extension is On.
- Default page when Edge starts: Blank New Tab.
- "Close all tabs?" dialog when closing Edge should be disabled.

Version: Edge 106.0.1370.47 / Blank New Tab 1.0.0

How to reproduce the problem:
1. Open a pdf file with Edge through the Windows file explorer.
2. Close Edge.
3. Inmediately open the same pdf file as before (or other).
4. Microsot Edge automatically closes.

Edge do not generate a crash report. Turning Off the Blank New Tab extension solves the problem (thus, Blank New Tab extension might be the problem).

**Comment by szanuj** [comment]
Thanks for reporting the issue and for providing the details.

Unfortunately, I don't think I can do anything about it. I tried to reproduce the problem - same version, specified settings, steps as described - but to no effect. It doesn't crash for me when I reopen a pdf. Tried with and without the extension, with and without additional performance settings on, just to check.

At the end of the day, the only thing this extension does is replace the new tab page, so I really have no idea how it could possibly affect anything else. Googling this problem I could see a couple threads about Edge crashes on opening pdfs but none of these were related to extensions.

Here are a few ideas of things you could try:

- Resetting Edge settings.
- Trying if the problem persists with a similar extension instead, such as [Minimal New Tab](https://microsoftedge.microsoft.com/addons/detail/minimal-new-tab/khdnagehanbomfdogegmpddmcalmdnbg).
- Reporting the issue to Edge with Send Feedback option.

**Comment by marcelomijas** [comment]
Thanks for the response. Amazingly, after resetting Edge, it started to doing it without the extension enabled (now I have no way to escape the problem...), so it should be an Edge's problem. Sorry for the inconvinience. Again, thanks!
