### ISSUE TITLE
It doesn't change new tabs in InPrivate

### ISSUE THREAD

**Issue by bywkgexmkiltxh** [szanuj/blank-new-tab#3]
because there's no option for _Allow in InPrivate_ in this extension's Details page

edit: I tried more extensions, and I saw some have the option _Allow in InPrivate_ in their Details pages but they fail to change New InPrivate tabs, except Google Arts & Culture which manages to hijack InPrivate tabs somehow

**Comment by szanuj** [comment]
From the relevant [chrome docs](https://developer.chrome.com/docs/extensions/develop/ui/override-chrome-pages#incognito):

> In incognito windows, extensions can't override New Tab pages.

I have checked, enabling Allow in InPrivate just doesn't do anything. Anyway, Incognito/InPrivate page isn't bloated with ads and news, so I don't feel a workaround is neccessary.

**Comment by bywkgexmkiltxh** [comment]
Thank you for your reply. I think the Bing search box is bloat but bearable. Also I see a contrasted box on the new tab icon's place for a moment before it turns into the new tab icon. The icon is a white box on dark mode, it's a dark box in white mode. Is this normal or a bug?

**Comment by szanuj** [comment]
Yeah, well, at least the bing search isn't focused.

As for the contrasted box, it's there, it's not intended, but I don't think I can do anything about it. The favicon is specified for light and dark mode directly in the html file, it should just work. Idk why the browser does this

**Comment by VanguardLH** [comment]
The inPrivate windows shows the Bing search bar. Bloat.  It also show a bunch of instructions. More bloat. New tabs in inPrivate mode are NOT blank.

Note: zmni's Blank Tab extension despite an option to run in inPrivate mode (and enabled) also has no effect in inPrivate mode.  With that extension, I still get the bloat in inPrivate mode: Bing search bar, and a bunch of instructions.

**Comment by szanuj** [comment]
It works fine for me ever since the change in #5 which corresponds to latest version on Edge Addons (1.1.3). Please make sure you have this version installed and enabled and Allow in InPrivate option is checked. Also under New Tab section in Settings, does it say that Blank New Tab controls new tab page?

**Comment by VanguardLH** [comment]
https://github.com/szanuj/blank-new-tab/pull/5 is 9 months old.  I just installed your extension about 4 hours ago (3 hours ago to add a report, and an hour to test it before the report): version 1.1.3, updated Oct 21, 2024.

Under edge://settings/startHomeNTP, the home page is configured to show the new-tab page, and it says it is controlled by your extension.  The New Tab Page setting also says it is controlled by your extension.  Because I have to use about:blank to redirect to the internal doc, I could configure the Home page to show about:blank instead of showing the new-tab page (controlled by your extension) since the effect is the same: show the about:blank page.

I've tried many blank tab extensions.  So far, only Redirect New Tab works in inPrivate mode.  Alas, it populates the address bar with whatever page that extension is configured to load, which in my case is about:blank.  Still, about:blank in the address bar is better than all the bloat in Microsoft's inPrivate new-tab page.

**Comment by szanuj** [comment]
Can you try and see if it works if you create a new profile, don't change any settings, install only this extension, enable it and check Allow in InPrivate? I just tried that and still no issue.

Is [this extension](https://github.com/jimschubert/NewTab-Redirect) the one that works for you? If so, the incognito setting in manifest.json is the same, so I don't know why it would be any different.

**Comment by VanguardLH** [comment]
Yes, https://github.com/jimschubert/NewTab-Redirect is the one that works to show a blank doc in inPrivate mode, but it also leaves the address populated with the URL specified to which it redirects (about:blank, in my case).

I created a new profile (which does not sign into my MS account), and installed only your extension.  Microsoft defaults to installing the Google Docs extension which I don't use, but I didn't bother to remove it for this test.  Now in an inPrivate window, I get a blank page (and blank address bar).  

Next test will be to disable all other add-ons in my normal profile (that does sign into my MS account), check if your extension works okay, and reenable them one at a time to determine if another extension is interfering with yours.  I have other extensions that are enabled to run in inPrivate mode.  

Get back soon.

**Comment by VanguardLH** [comment]
I disabled all extensions except yours, and exited to restart Edge to ensure everything got cleared (Edge is configured to purge all locally cached data except passwords).  Your extension did NOT present a blank doc in an inPrivate window.  

I had Edge configured to use Balanced tracking prevention in a normal web session.  However, Strict tracking prevention was enabled for inPrivate mode.  I disabled that, restarted Edge, but still got a polluted new-tab page in inPrivate mode.

I do NOT allow Edge to pre-load the new-tab page, but your extension disables that option, anyway.

Javascript permission is allowed, and no blocks in its exception list.  Images permission is to show all.  Popup permission (blocking) was enabled, but disabling it did not get your extension to give me a blank new-tab in inPrivate mode.  Intrusive ads (blocking) was enabled, but disabling it did not help your extension.  I had disabled the protocol handlers permission, but enabling it didn't help your extension.  I changed some other permissions, but none got your extension to work in inPrivate mode.

Preloading of web pages is disabled.

Startup boost (leaving ms-edge.exe processes running on exit) is disabled.

Continue running apps in background is disabled.

Sleeping tabs is disabled.

I reviewed other settings, and either they did not seem applicable, or changing them did not help your extension to work in inPrivate mode.

**Comment by VanguardLH** [comment]
By the way, another blank-tab extension that works with my current Edge profile (the normal one, not a new default one) is Blank New Tab Page - White Smoke (https://github.com/szanuj/blank-new-tab/issues/3#issuecomment-2901584026).  That gives me a blank new-tab in inPrivate mode, and with a blank address bar.  So, I've found 2 blank-tab extensions that work in inPrivate mode with my current Edge configuration, and with all the other extensions enabled.

I don't think just changing the manifest (to support v3) is all that is needed to get an extension to work correctly in inPrivate mode.  While a fresh Edge profile got your extension working, I'm not sure anyone using your extension would have all the default settings in a profile.  If they've added extensions, they've probably also tweaked the web browser.  Alas, I could not find which tweak confounds your extension in inPrivate mode, but then a couple other extensions work with how my Edge is configured.

Note: The only test that I have not performed, so far, is to NOT login to my MS account in my Edge profile.  However, even if that gets your extension working in inPrivate mode, I won't be using Edge that way.  I need it to login to have its sync function operate to get Edge elsewhere to be in sync.

**Comment by szanuj** [comment]
Uninstall my extension and try this - [blank-new-tab-storage.zip](https://github.com/user-attachments/files/20399165/blank-new-tab-storage.zip). Unpack into a folder, go to Extensions, enable Developer mode, choose Load unpacked and select the folder with "manifest.json" in it. Then enable extension - name will be "Blank New Tab (storage)", and check Allow in InPrivate.

I added storage permission declaration to manifest. I don't use storage API but your two working addons do use it and one mentioned storage API in context of incognito, so maybe it's that?

My extension is very simple, it's just an HTML page and a few lines of JS to set title language. If Edge shows you its bloated new tab page, it must be something about manifest or your settings (or another new tab extension active at the same time). I use my addon while logged into MS sync and alongside other extensions, my settings far from default too, but it works fine.

**Comment by VanguardLH** [comment]
I downloaded your .zip file, and loaded the unpacked extension (I already have developer mode enabled, but I don't remember why).  I enabled your extension (with the "storage" postfix) to run in inPrivate mode.  Now I get a blank new tab in inPrivate mode (and coincidentally a blank address bar which the New Tab Redirect extension left populated with about:blank).  So, something about running the extension in inPrivate mode needed storage permission.  

I will disable the New Tab Redirect extension and just go forward with yours to verify it continues working in inPrivate mode.  Presumably you will update the extension to incorporate this change.

**Comment by VanguardLH** [comment]
Alas, a side effect of installing your extension in Developer Mode is getting a prompt warning about running dev mode extensions.  See:

https://support.microsoft.com/en-us/topic/developer-mode-extension-notification-b8c45464-6245-4137-94cb-f478aa6c9ab1

The warning cannot be disabled, and I'm not wasting time with betaware versions of any web browser.  I disable Developer mode for extensions in Edge, and will test if your "storage 1.1.3" version continues to function.

UPDATE

Nope, disabling Developer mode does not get rid of the nag.  Whenever your extension activates, I get the nag.  The only option is to turn off any extensions that run in Dev mode which means your "storage" version gets disabled.  I'll uninstall your "storage" version, and await until you update your extension (to not require Dev mode).

**Comment by szanuj** [comment]
Glad to have this chrome quirk sorted out. Iirc developer mode nag pops up every 2 weeks or so. I will update the store version now and it will be there after review which might take a week or so.

**Comment by VanguardLH** [comment]
Announce the new version here, so I get notified there a released new version.  Eager to try it out.

By the way, I got the dev nag everytime I started Edge, and your extension fired.  It wasn't every 2 weeks.  Twas every time your extension got used (once per web session).

**Comment by szanuj** [comment]
New version is live

**Comment by VanguardLH** [comment]
Disable New Tab Redirect, installed yours, and enabled to run in inPrivate mode.  It works now.  In inPrivate mode, I get a blank new-tab page, and the address bar is also blank.  Thanks for resolving this issue.  Nice to know an extension author is active and responsive.

**Comment by bywkgexmkiltxh** [comment]
Wicked microsoft has done something and now the extension doesn't work on InPrivate. Current version 146.0.3856.72. Allow in InPrivate ticked...

**Comment by szanuj** [comment]
can confirm. annoying, but seems there's nothing we can do...
